<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <OPENCV_BASE_DIR>D:\DEV_EXEC\libs\opencv\build</OPENCV_BASE_DIR>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <Link>
      <AdditionalLibraryDirectories>$(OPENCV_BASE_DIR)\x64\vc16\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>opencv_world500.lib;opencv_world500d.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <ClCompile>
      <AdditionalIncludeDirectories>$(OPENCV_BASE_DIR)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="OPENCV_BASE_DIR">
      <Value>$(OPENCV_BASE_DIR)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>